project: 
  type: website
  output-dir: docs

website:
  title: "Mohammed Zuber's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Synthetic Data Exercise"
            file: synthetic-data-exercise/synthetic data exercise.qmd
    right:
      - icon: github 
        href: https://github.com/mohammedzuber099/mohammedzuber-MADA-portfolio        
format:
  html:
    theme: flatly
    highlight: zenburn
    css: styles.css
    toc: FALSE